# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-20 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='crete_time',
            new_name='create_time',
        ),
    ]
